version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - build-linux
      - build-mac

jobs:
  build-linux:
    resource_class: large
    docker:
      - image: nixos/nix:2.3.12
        environment:
          CACHIX_NAME: vulcanclimatemodeling
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b4:dc:1c:be:13:6b:e6:32:33:4f:d9:0c:a6:d9:57:40"
      - checkout
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash nixpkgs.git nixpkgs.openssl
            cachix authtoken $CACHIX_AUTH_TOKEN
            cachix use $CACHIX_NAME
            nix path-info --all > /tmp/store-path-pre-build
      - run:
          name: pre-commit
          command: nix-build release.nix -A pre-commit-check
      - run:
          name: Build
          command: nix-build --max-jobs 4 --verbose release.nix
      - run:
          name: Push to Cachix
          command: |
            bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push $CACHIX_NAME"
  build-mac:
    macos:
      xcode: 13.2.0
    environment:
      CACHIX_NAME: vulcanclimatemodeling
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b4:dc:1c:be:13:6b:e6:32:33:4f:d9:0c:a6:d9:57:40"
      - run:
          name: Install Nix
          command: |
            echo "" >> $HOME/.bash_profile
            sh <(curl -L https://releases.nixos.org/nix/nix-2.3.16/install) --darwin-use-unencrypted-nix-store-volume --no-daemon
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash nixpkgs.git nixpkgs.openssl
            cachix authtoken $CACHIX_AUTH_TOKEN
            cachix use $CACHIX_NAME
            nix path-info --all > /tmp/store-path-pre-build
      - checkout
      - run:
          name: Build
          command: nix-build --max-jobs 4 --verbose release.nix
      - run:
          name: Push to Cachix
          command: |
            bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push $CACHIX_NAME"
