version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - build-linux
      - build-mac

jobs:
  build-linux:
    resource_class: large
    docker:
      - image: nixos/nix:2.3.12
        environment:
          CACHIX_NAME: vulcanclimatemodeling
    steps:
      - checkout
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash nixpkgs.git nixpkgs.openssl
            cachix authtoken $CACHIX_AUTH_TOKEN
            cachix use $CACHIX_NAME
            nix path-info --all > /tmp/store-path-pre-build
      - run:
          name: pre-commit
          command: nix-build release.nix -A pre-commit-check
      - run:
          name: Build
          command: nix-build --max-jobs 4 --verbose release.nix
      - run:
          name: Push to Cachix
          command: |
            bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push $CACHIX_NAME"
  build-mac:
    macos:
      xcode: 11.3.0
    environment:
      CACHIX_NAME: vulcanclimatemodeling
    steps:
      - run:
          name: Install Nix
          command: |
            curl -k https://curl.se/ca/cacert.pem -o ~/.cacert.pem
            export CURL_CA_BUNDLE=~/.cacert.pem
            curl -L -O https://nixos.org/nix/install
            sh install --no-daemon
            rm -f install
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash nixpkgs.git nixpkgs.openssl
            cachix authtoken $CACHIX_AUTH_TOKEN
            cachix use $CACHIX_NAME
            nix path-info --all > /tmp/store-path-pre-build
      - checkout
      - run:
          name: Build
          command: nix-build --max-jobs 4 --verbose release.nix
      - run:
          name: Push to Cachix
          command: |
            bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push $CACHIX_NAME"
